### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by mrDinckleman** [manierim/ingressplanner#14]
Hello.
I really like your instrument, thanks to him I received a large number of AP. 
Therefore, I would like to offer my help in supporting this project, because I believe that the community is interested in actively implementing new features, fixing possible bugs and improving its usability.

**Comment by manierim** [comment]
Hi Sergey,

sure. I already merged a few of your commits after fixing a problem on my dev machine that was making impossibile to run tests.

Now I fixed it and I'll be much faster in checking and merging pull requests, please keep sending them!
