### ISSUE TITLE
Steps tab

### ISSUE THREAD

**Issue by jpveneracion** [manierim/ingressplanner#15]
hi. first of all thanks for the awesome planning helper.
however as of today i cannot see the steps tab working. no steps added and just an X in the planning tab. 

Is this a known issue or just my google account? thanks and God bless.

**Comment by manierim** [comment]
On my two Windows 10 PCs with Chrome 73.0.3683.103 it does works fine at least loading existing plans.

Are you loading and existing plan?
Are you able to use, if available in your browser, the javascript console to locate any error or warning that could help identify the issue?

**Comment by jpveneracion** [comment]
hi. i tried on firefox and chrome. removed all userscripts and tried again. on firefox it has this red error

`Content Security Policy: The page’s settings observed the loading of a resource at eval (“script-src”). `

and on chrome no red error but these warning lines.

`ingressplanner.js:1213 * Ingress Planner Queued OUTGOING message update-drawing {drawing: Array(0)}
consoleout @ ingressplanner.js:1213
warn @ ingressplanner.js:1319
_sendMessage @ iitc.js:45
sendMessage @ iitc.js:123
loadAndAnalyzePlan @ ingressplanner.js:1234
v2manage @ ingressplanner.js:1101
trigger @ ingressplanner.js:1125
gdriveEventHandler @ ingressplanner.js:1187
loadedPlan @ gdrive.js:407
callBack @ gdrive.js:427
(anonymous) @ gdrive.js:432
(anonymous) @ gdrive.js:293
(anonymous) @ cb=gapi.loaded_0:704
(anonymous) @ cb=gapi.loaded_0:699
(anonymous) @ cb=gapi.loaded_0:688
(anonymous) @ cb=gapi.loaded_0:211
E.__cb @ cb=gapi.loaded_0:147
g @ cb=gapi.loaded_0:141
c @ cb=gapi.loaded_0:137`
`ingressplanner.js:1213 * Ingress Planner Queued OUTGOING message center-drawing undefined
consoleout @ ingressplanner.js:1213
warn @ ingressplanner.js:1319
_sendMessage @ iitc.js:45
sendMessage @ iitc.js:123
v2manage @ ingressplanner.js:1103
trigger @ ingressplanner.js:1125
gdriveEventHandler @ ingressplanner.js:1187
loadedPlan @ gdrive.js:407
callBack @ gdrive.js:427
(anonymous) @ gdrive.js:432
(anonymous) @ gdrive.js:293
(anonymous) @ cb=gapi.loaded_0:704
(anonymous) @ cb=gapi.loaded_0:699
(anonymous) @ cb=gapi.loaded_0:688
(anonymous) @ cb=gapi.loaded_0:211
E.__cb @ cb=gapi.loaded_0:147
g @ cb=gapi.loaded_0:141
c @ cb=gapi.loaded_0:137
VM589:13952 cancelling existing map refresh timer`

**Comment by jpveneracion** [comment]
Thanks. I really miss the steps tab working. :)

**Comment by manierim** [comment]
From the Chrome output seems like the google drive APIs can't get a valid plan first and then they just get an empty plan.

Check your selected plan in the Plans tab to be sure it is a not empty one.

Also check ingressplanner is still authorized to access your google drive. Go to drive website -> Settings (icon top right) -> Manage applications (my drive is in Italian, I translated on the fly,look for the general meaning, not exact words).
