### ISSUE TITLE
ingress planner website.

### ISSUE THREAD

**Issue by michaelm1745** [manierim/ingressplanner#16]
hi,

I really love what you did for the community. recently the site has been offline.
is it coming back? did you abandon this project?

**Comment by manierim** [comment]
Hi Michael,

sorry we had a major issue on the server that was (also) hosting ingressplanner.net.

We are now moving our work service to other platforms, then I'll find a new home for ingressplanner.net.

It will take some days. Work stuff have priority....

**Comment by michaelm1745** [comment]
no worries, work/life takes precedence. 
I really appreciate the work you have done.

thanks in advance

**Comment by manierim** [comment]
Hi Michael,

happy to inform that https://www.ingressplanner.net is back online!
