### ISSUE TITLE
More periodic saves 

### ISSUE THREAD

**Issue by Krandor1** [manierim/ingressplanner#6]
I've had a few times when I've been working on a plan and then my browser will mess up and when I go back I am half and hour to an hour back from where I started.   So more frequent saves (or an optio to set how often to save) would be great.

**Comment by manierim** [comment]
Hi Krandor1. The plan get saved every time there is any change to it (i.e. add, remove, change any plan item).

Only problem with saving is that after a long idle time the Google drive connection get broken and the saves are not performed.

Currently I've not been able to change the code in order detect this situation and re-establish a working connection.

Workaround is to reload the Ingress Planner page after a long idle and before making any changeto the plan.
